import { markRaw } from 'vue'
import {
  Bot,
  BookOpen,
  Brain,
  Braces,
  Bug,
  Calendar,
  Check,
  CircleHelp,
  Clock,
  Cloud,
  Code,
  Cog,
  Cookie,
  Cpu,
  Database,
  Eye,
  File,
  FileCode,
  FilePen,
  FileText,
  FlaskConical,
  Folder,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Image,
  Key,
  Layers,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  Mail,
  MessageSquare,
  Monitor,
  Network,
  Package,
  PencilLine,
  Play,
  Plus,
  Puzzle,
  Repeat,
  Route,
  Search,
  Send,
  Server,
  ShieldCheck,
  Smartphone,
  SquareTerminal,
  Table,
  User,
  Users,
  Wrench,
  X,
  Zap,
} from '@lucide/vue'

// The fixed icon set of icon-names.js, as Lucide components.
const ICONS = {
  user: User,
  users: Users,
  brain: Brain,
  bot: Bot,
  file: File,
  'file-code': FileCode,
  'file-text': FileText,
  'file-pen': FilePen,
  folder: Folder,
  terminal: SquareTerminal,
  code: Code,
  braces: Braces,
  database: Database,
  server: Server,
  globe: Globe,
  cloud: Cloud,
  route: Route,
  cog: Cog,
  shield: ShieldCheck,
  lock: Lock,
  key: Key,
  search: Search,
  message: MessageSquare,
  mail: Mail,
  book: BookOpen,
  'list-checks': ListChecks,
  check: Check,
  x: X,
  help: CircleHelp,
  plus: Plus,
  clock: Clock,
  calendar: Calendar,
  layers: Layers,
  cpu: Cpu,
  monitor: Monitor,
  smartphone: Smartphone,
  network: Network,
  package: Package,
  'git-branch': GitBranch,
  play: Play,
  zap: Zap,
  link: Link,
  hammer: Hammer,
  'graduation-cap': GraduationCap,
  eye: Eye,
  cookie: Cookie,
  pencil: PencilLine,
  flask: FlaskConical,
  image: Image,
  table: Table,
  repeat: Repeat,
  puzzle: Puzzle,
  wrench: Wrench,
  bug: Bug,
  send: Send,
  lightbulb: Lightbulb,
}

for (const name in ICONS) ICONS[name] = markRaw(ICONS[name])

export const iconFor = (name) => (name ? ICONS[name] : undefined)
