import {
  siOpenjdk,
  siSpring,
  siSpringboot,
  siVuedotjs,
  siReact,
  siJavascript,
  siTypescript,
  siPython,
  siFastapi,
  siNodedotjs,
  siDocker,
  siGit,
  siGithub,
  siGitlab,
  siPostgresql,
  siMysql,
  siMariadb,
  siSqlite,
  siMongodb,
  siRedis,
  siSupabase,
  siFirebase,
  siHtml5,
  siCss,
  siTailwindcss,
  siBootstrap,
  siSass,
  siVite,
  siNpm,
  siPnpm,
  siLinux,
  siUbuntu,
  siAndroid,
  siKotlin,
  siPhp,
  siLaravel,
  siNginx,
  siApachetomcat,
  siThymeleaf,
  siGradle,
  siApachemaven,
  siHibernate,
  siIntellijidea,
  siPostman,
  siFigma,
  siAnthropic,
  siClaude,
  siClaudecode,
  siOpencode,
  siGooglegemini,
  siDeepseek,
  siOllama,
  siHuggingface,
  siLangchain,
  siOpenrouter,
  siJson,
  siMarkdown,
  siAngular,
  siSvelte,
  siNuxt,
  siNextdotjs,
  siAstro,
  siExpress,
  siNestjs,
  siDjango,
  siFlask,
  siJquery,
  siGraphql,
  siJest,
  siVitest,
  siJunit5,
  siSelenium,
  siKubernetes,
  siJenkins,
  siGithubactions,
  siSwagger,
  siVercel,
  siNetlify,
  siCloudflare,
  siDart,
  siFlutter,
  siSwift,
  siDotnet,
  siGo,
  siRust,
  siPinia,
  siMoodle,
  siObsidian,
  siNotion,
  siDiscord,
  siMacos,
} from 'simple-icons'

// Technology logos for Logos(names), from simple-icons: a fixed set, imported one by one so
// the bundle only carries these. A name is matched on its title, loosely ("Vue", "Vue.js" and
// "vuejs" all find Vue.js), with a few common aliases. A name not here shows without a logo.
const ICONS = [
  siOpenjdk,
  siSpring,
  siSpringboot,
  siVuedotjs,
  siReact,
  siJavascript,
  siTypescript,
  siPython,
  siFastapi,
  siNodedotjs,
  siDocker,
  siGit,
  siGithub,
  siGitlab,
  siPostgresql,
  siMysql,
  siMariadb,
  siSqlite,
  siMongodb,
  siRedis,
  siSupabase,
  siFirebase,
  siHtml5,
  siCss,
  siTailwindcss,
  siBootstrap,
  siSass,
  siVite,
  siNpm,
  siPnpm,
  siLinux,
  siUbuntu,
  siAndroid,
  siKotlin,
  siPhp,
  siLaravel,
  siNginx,
  siApachetomcat,
  siThymeleaf,
  siGradle,
  siApachemaven,
  siHibernate,
  siIntellijidea,
  siPostman,
  siFigma,
  siAnthropic,
  siClaude,
  siClaudecode,
  siOpencode,
  siGooglegemini,
  siDeepseek,
  siOllama,
  siHuggingface,
  siLangchain,
  siOpenrouter,
  siJson,
  siMarkdown,
  siAngular,
  siSvelte,
  siNuxt,
  siNextdotjs,
  siAstro,
  siExpress,
  siNestjs,
  siDjango,
  siFlask,
  siJquery,
  siGraphql,
  siJest,
  siVitest,
  siJunit5,
  siSelenium,
  siKubernetes,
  siJenkins,
  siGithubactions,
  siSwagger,
  siVercel,
  siNetlify,
  siCloudflare,
  siDart,
  siFlutter,
  siSwift,
  siDotnet,
  siGo,
  siRust,
  siPinia,
  siMoodle,
  siObsidian,
  siNotion,
  siDiscord,
  siMacos,
]

const key = (name) => String(name).toLowerCase().replace(/[^a-z0-9+#]/g, '')

const BY_NAME = new Map(ICONS.map((icon) => [key(icon.title), icon]))
const ALIASES = {
  java: siOpenjdk,
  vue: siVuedotjs,
  vuejs: siVuedotjs,
  node: siNodedotjs,
  nodejs: siNodedotjs,
  next: siNextdotjs,
  nextjs: siNextdotjs,
  postgres: siPostgresql,
  maven: siApachemaven,
  tomcat: siApachetomcat,
  intellij: siIntellijidea,
  gemini: siGooglegemini,
  html: siHtml5,
  css3: siCss,
  tailwind: siTailwindcss,
  golang: siGo,
  net: siDotnet,
  junit: siJunit5,
  githubaction: siGithubactions,
  spring: siSpring,
}
for (const [alias, icon] of Object.entries(ALIASES)) BY_NAME.set(alias, icon)

/** The simple-icons entry for a technology name, or undefined. */
export const logoFor = (name) => BY_NAME.get(key(name))
