-- The class's weekly timetable, for everyone to see (not the daily pass's own schedule,
-- which is pass_*). On or off, the days' names, when the week starts and ends (HH:MM, the
-- class's own timezone) and the breaks that run across every day. Also in schema.sql.
alter table settings add column if not exists schedule_enabled boolean not null default false;
alter table settings add column if not exists schedule_days text[] not null default '{Monday,Tuesday,Wednesday,Thursday,Friday}';
alter table settings add column if not exists schedule_start text not null default '08:10';
alter table settings add column if not exists schedule_end text not null default '15:20';
alter table settings add column if not exists schedule_breaks jsonb not null default '[]';
-- A real session's length in minutes, so dragging a slot in Admin always lands on a real
-- session (one, or two back to back), never an odd length.
alter table settings add column if not exists schedule_session_minutes smallint not null default 50;

-- One slot in the week: a class, a shift, a meeting. `node_id` links it to a page or section
-- (its title and colour are used when the slot has none of its own); null for a slot with no
-- page, such as a subject the class notes don't cover.
create table if not exists schedule_events (
  id bigint generated by default as identity primary key,
  node_id bigint references nodes(id) on delete set null,
  day smallint not null check (day >= 0 and day <= 6),
  start_time text not null,
  end_time text not null,
  title text,
  detail text,
  color text,
  created_at timestamptz not null default now()
);

alter table schedule_events enable row level security;
-- No public policies: like nodes and notes, only the backend (service role) reads and writes.
